export const GET_CART_DETAILS = "APP/CART_PAGE/GET_CART_DETAILS";
export const GET_CART_DETAILS_SUCCESS = "APP/CART_PAGE/GET_CART_DETAILS_SUCCESS";
export const GET_CART_DETAILS_FAILURE = "APP/CART_PAGE/GET_CART_DETAILS_FAILURE";

// export const RESET_CART_TO_INITIAL_STATE = "APP/CHECKOUT_PAGE/RESET_CART_TO_INITIAL_STATE";

export const GET_SEARCH_VALUE = "APP/GET_SEARCH_VALUE/GET_SEARCH_VALUE";
export const GET_SEARCH_VALUE_SUCCESS = "APP/GET_SEARCH_VALUE/GET_SEARCH_VALUE_SUCCESS";
export const GET_SEARCH_VALUE_FAILURE = "APP/GET_SEARCH_VALUE/GET_SEARCH_VALUE_FAILURE";

// export user details

export const GET_USER_DETAILS = "APP/GET_USER_DETAILS/GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "APP/GET_USER_DETAILS/GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "APP/GET_USER_DETAILS/GET_USER_DETAILS_FAILURE";




